apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: printenv
spec:
  hosts:
    - printenv.istio-test.svc.cluster.local
  http:
    - name: "chain-1"
      match:
        - sourceLabels:
            app: nettools
            chain: v1
      route:
        - destination:
            host: printenv.istio-test.svc.cluster.local
            subset: v1
    - name: "chain-2"
      match:
        - sourceLabels:
            app: nettools
            chain: v2
      route:
        - destination:
            host: printenv.istio-test.svc.cluster.local
            subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: printenv
spec:
  host: printenv.istio-test.svc.cluster.local
  subsets:
    - name: chain-1
      labels:
        chain: v1
        version: v1
    - name: chain-2
      labels:
        version: v2
        chain: v2
