apiVersion: v1
kind: Pod
metadata:
  name: printenv
  namespace: istio-test
spec:
  containers:
    - name: envoy-test
      image: louhwz/envoy_test:0.0.2
      env:
      - name: printwhat
        value: "影魔"
      resources:
        limits:
          cpu: 20m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
      - containerPort: 80
  restartPolicy: Always

