apiVersion: v1
kind: Pod
metadata:
  name: printenv-jugg
  namespace: istio-test
spec:
  containers:
    - name: printenv
      image: louhwz/printenv:0.0.3
      env:
      - name: printwhat
        value: "剑圣"
      resources:
        limits:
          cpu: 20m
          memory: 50Mi
        requests:
          cpu: 20m
          memory: 50Mi
      ports:
      - containerPort: 80
  restartPolicy: Always

