apiVersion: v1
kind: Pod
metadata:
  name: envoy-test
  namespace: default
spec:
  containers:
    - name: envoy-test
      image: louhwz/envoy_test
      ports:
      - containerPort: 80
  restartPolicy: Always
